services:
  sql-data:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=masterkey@A
      - ACCEPT_EULA=Y
      - HOMEBREW_NO_ENV_FILTERING=1
    ports:
      - "1433:1433"